### ISSUE TITLE
[Bug]: Debian, Firefox, and Pinball do not work.

### ISSUE THREAD

**Issue by uhidontkno** [spaceness/stardust-images#11]
Will make PR once I figure out diagnosis.

**Comment by incognitotgt** [comment]
Debian seems to be broken for some reason. firefox works for me ...?
pinball is x86 only

**Comment by uhidontkno** [comment]
Most x86 software should work on x64, but the Pinball Linux port works fine on x64.

Jul 21, 2024 11:18:45 PM tgt ***@***.***>:

**Comment by incognitotgt** [comment]
Pinball works for me on https://st.spaceness.one so idk about that
idk why debian's broken for me, some script prolly got borked
firefox also works

**Comment by incognitotgt** [comment]
ok so
* pinball's build failed, i'll fix tmrw
* debian is broken
* and chromium is,.,.chromium
